# Generated by Django 3.1.3 on 2021-04-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20210421_0109'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('diagnose_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='诊断id')),
                ('diagnose_text', models.TextField(blank=True, null=True, verbose_name='诊断信息')),
                ('diagnose_date', models.DateField(verbose_name='诊断时间')),
                ('fee_id', models.CharField(max_length=100, verbose_name='收费id')),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.medicine', verbose_name='开药id')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientbase', verbose_name='病人号')),
            ],
            options={
                'verbose_name': '诊断信息',
                'verbose_name_plural': '诊断信息',
            },
        ),
        migrations.AlterField(
            model_name='register',
            name='register_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='挂号id'),
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('fee_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='收费单id')),
                ('fee_content', models.CharField(max_length=200, verbose_name='收费明细')),
                ('fee_total', models.FloatField(verbose_name='收费金额')),
                ('fee_date', models.DateField(verbose_name='收费时间')),
                ('diagnose_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.diagnose', verbose_name='诊断id')),
                ('register_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.register', verbose_name='挂号id')),
            ],
            options={
                'verbose_name': '收费流水',
                'verbose_name_plural': '收费流水',
            },
        ),
        migrations.AddField(
            model_name='diagnose',
            name='register_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.register', verbose_name='挂号id'),
        ),
    ]
