# Generated by Django 3.1.3 on 2021-04-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20210421_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnose',
            name='medicine_id',
            field=models.CharField(max_length=50, verbose_name='开药id'),
        ),
        migrations.AlterField(
            model_name='diagnose',
            name='report_id',
            field=models.CharField(default='REPORT0', max_length=50, verbose_name='检查id'),
        ),
    ]
