# Generated by Django 3.1.3 on 2021-06-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_fee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '未缴费'), (1, '已缴费')], default=0, verbose_name='缴费状态'),
        ),
    ]
