# Generated by Django 3.1.3 on 2021-04-20 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='科室号')),
                ('dept_name', models.CharField(max_length=50, verbose_name='科室名')),
            ],
            options={
                'verbose_name': '科室',
                'verbose_name_plural': '科室',
            },
        ),
        migrations.CreateModel(
            name='DoctorBase',
            fields=[
                ('doc_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='医生号')),
                ('doc_name', models.CharField(max_length=50, unique=True, verbose_name='医生名字')),
                ('doc_title', models.CharField(max_length=50, verbose_name='医生职称')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.department', verbose_name='科室号')),
            ],
            options={
                'verbose_name': '医生基本信息',
                'verbose_name_plural': '医生基本信息',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='dept_directcor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorbase', verbose_name='科室主任'),
        ),
    ]
