# Generated by Django 3.1.3 on 2021-04-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('check_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='检查项目id')),
                ('check_name', models.CharField(max_length=50, verbose_name='检查项目名字')),
                ('check_price', models.IntegerField(verbose_name='检查价格')),
            ],
            options={
                'verbose_name': '检查价格信息',
                'verbose_name_plural': '检查价格信息',
            },
        ),
        migrations.AlterField(
            model_name='medicine',
            name='med_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='药品id'),
        ),
    ]
