# Generated by Django 3.1.3 on 2021-04-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20210421_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkitem',
            options={'verbose_name': '检查价格', 'verbose_name_plural': '检查价格'},
        ),
    ]
