# Generated by Django 3.1.3 on 2021-04-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20210421_1409'),
        ('doctor', '0005_check_checkdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('remark_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='评价id')),
                ('remark_date', models.DateField(verbose_name='评价时间')),
                ('remark', models.TextField(verbose_name='评价内容')),
                ('score', models.FloatField(verbose_name='评价得分')),
                ('diagnose_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.diagnose', verbose_name='诊断id')),
            ],
        ),
    ]
