# Generated by Django 3.1.3 on 2021-04-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_roster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remark',
            options={'verbose_name': '药品价格信息', 'verbose_name_plural': '药品价格信息'},
        ),
        migrations.AlterField(
            model_name='doctorbase',
            name='doc_name',
            field=models.CharField(max_length=50, verbose_name='医生名字'),
        ),
    ]
