# Generated by Django 3.1.3 on 2021-04-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20210428_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorbase',
            name='dept_id',
            field=models.IntegerField(verbose_name='科室号'),
        ),
    ]
