# Generated by Django 3.1.3 on 2021-04-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_auto_20210428_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_director',
            new_name='doc_id',
        ),
    ]
