# Generated by Django 3.1.3 on 2021-05-24 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_auto_20210428_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remark',
            options={'verbose_name': '医生评价信息', 'verbose_name_plural': '医生评价信息'},
        ),
        migrations.AddField(
            model_name='remark',
            name='doctor_id',
            field=models.ForeignKey(default='10001', on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorbase', verbose_name='医生id'),
        ),
    ]
