# Generated by Django 3.1.3 on 2021-05-24 04:01

from django.db import migrations, models
import doctor.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_auto_20210524_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorbase',
            name='doc_mail',
            field=models.EmailField(default=doctor.models.random_mail, max_length=254, verbose_name='医生邮箱'),
        ),
    ]
