# Generated by Django 3.1.3 on 2021-05-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_doctorbase_doc_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkitem',
            name='check_info',
            field=models.CharField(default=1, max_length=100, verbose_name='检查相关信息'),
            preserve_default=False,
        ),
    ]
