# Generated by Django 3.1.3 on 2021-06-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_checkitem_check_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkdetail',
            name='check_status',
            field=models.PositiveIntegerField(choices=[(0, '未缴费'), (1, '已缴费'), (2, '已完成')], default=0, verbose_name='检查状态'),
        ),
    ]
