# Generated by Django 3.1.3 on 2021-06-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_checkdetail_check_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkdetail',
            name='check_status',
        ),
    ]
